config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :order_lines
  resources :places do
    resources :tickets
  end
  root 'dashboard#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :place
  has_many :order_lines
  has_many :orders, through: :order_lines

  validates :name, presence: true
  validates_uniqueness_of :name, :scope => :place_id
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_place
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = @place.tickets
    respond_to do |format|
      format.js
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = @place.tickets.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
        format.js do 
          @tickets = @place.tickets
          render "create"
        end
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
        format.js do
          @errors = @ticket.errors
          render "layouts/errors"
        end
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
        format.js do 
          @tickets = @place.tickets
          render "create"
        end
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
        format.js do
          @errors = @ticket.errors
          render "layouts/errors"
        end
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
      format.js do 
        @tickets = @place.tickets
        render "create"
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    def set_place
      @place = Place.find(params[:place_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:name, :price, :place_id)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_all_ticket.html.slim
.col-md-5
  label チケット名
.col-md-3
  label 価格
- @place.tickets.each do |tk|
  = form_for [@place, tk], remote: true do |f|
    .col-md-5
      = f.text_field :name, class: "form-control"
    .col-md-3
      = f.number_field :price, class: "form-control"
    .col-md-3 style="display: inline-flex"
      = f.submit "保存", class: "btn btn-primary", type: "submit"
      = link_to '削除', [@place, tk], data: { confirm: '本当に削除しますか?' }, method: :delete, remote: true, class: "btn btn-danger"
- ticket = @place.tickets.new
= form_for [@place, ticket], remote: true do |f|
  .col-md-5
    = f.text_field :name, class: "form-control"
  .col-md-3
    = f.number_field :price, class: "form-control"
  .col-md-2
    = f.submit "作成", class: "btn btn-primary", type: "submit"

app/views/tickets/_form.html.slim
= form_for [@place, @ticket] do |f|
  - if @ticket.errors.any?
    #error_explanation
      h2 = "#{pluralize(@ticket.errors.count, "error")} prohibited this ticket from being saved:"
      ul
        - @ticket.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :price
    = f.number_field :price
  .field
    = f.label :place
    = f.text_field :place
  .actions = f.submit

app/views/tickets/_tickets_list_modal.html.slim
- if @place.present?
  #ticket-modal.modal.fade tabindex="-1" role="dialog" aria-labelledby="PlaceModal" aria-hidden="true" data-link=""
    .modal-dialog
      .modal-content
        .modal-header
          button.close type="button" data-dismiss="modal"
            span aria-hidden="true" &times;
            span.sr-only Close
          h4#ticket-modal-label.modal-title = "#{@place.name}のチケット管理"
        #all_ticket.modal-body style="height: 500px; overflow: scroll;"
          = render "all_ticket"

app/views/tickets/create.js.slim
|

  var all_ticket = "#{j render partial: "all_ticket"}"
  $("#all_ticket").html(all_ticket)

app/views/tickets/edit.html.slim
h1 Editing ticket

== render 'form'

=> link_to 'Show', @ticket
'|
=< link_to 'Back', tickets_path

app/views/tickets/index.html.slim
h1 Listing tickets

table
  thead
    tr
      th Name
      th Price
      th Place
      th
      th
      th

  tbody
    - @tickets.each do |ticket|
      tr
        td = ticket.name
        td = ticket.price
        td = ticket.place
        td = link_to 'Show', ticket
        td = link_to 'Edit', edit_ticket_path(ticket)
        td = link_to 'Destroy', ticket, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Ticket', new_place_ticket_path(@place)

app/views/tickets/index.js.slim
|

  var tickets_list_modal = "#{j render partial: "tickets_list_modal"}"
  $("#tickets-list").html(tickets_list_modal)
  $("#ticket-modal").modal("show")

app/views/tickets/new.html.slim
h1 New ticket

== render 'form'

= link_to 'Back', place_tickets_path(@place)

app/views/tickets/show.html.slim
p#notice = notice

p
  strong Name:
  = @ticket.name
p
  strong Price:
  = @ticket.price
p
  strong Place:
  = @ticket.place

=> link_to 'Edit', edit_ticket_path(@ticket)
'|
=< link_to 'Back', tickets_path