config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :order_lines
  resources :places do
    resources :tickets
  end
  root 'dashboard#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order_line.rb
class OrderLine < ApplicationRecord
  belongs_to :order
  belongs_to :ticket
end

app/controllers/order_lines_controller.rb
class OrderLinesController < ApplicationController
  before_action :set_order_line, only: [:show, :edit, :update, :destroy]

  # GET /order_lines
  # GET /order_lines.json
  def index
    @order_lines = current_user.pending_order.order_lines.where("quantity > ?", 0)
    @order = current_user.pending_order
  end

  # GET /order_lines/1
  # GET /order_lines/1.json
  def show
  end

  # GET /order_lines/new
  def new
    @order_line = OrderLine.new
  end

  # GET /order_lines/1/edit
  def edit
  end

  # POST /order_lines
  # POST /order_lines.json
  def create
    order = current_user.pending_order
    @order_line = order.order_lines.find_or_create_by(ticket_id: params[:ticket_id])
    old_quantity = @order_line.quantity.to_i
    base_quantity =  params[:type] == "add" ? @order_line.quantity.to_i : 0
    @order_line.quantity = base_quantity + params[:quantity].to_i

    respond_to do |format|
      if @order_line.save
        total_amount = order.total_amount.to_i + @order_line.ticket.price * (params[:quantity].to_i - old_quantity)
        order.update total_amount: total_amount
        format.html { redirect_to @order_line, notice: 'Order line was successfully created.' }
        format.json { render :show, status: :created, location: @order_line }
        format.js
      else
        format.html { render :new }
        format.json { render json: @order_line.errors, status: :unprocessable_entity }
        format.js do
          @errors = @order_line.errors
          render "layouts/errors"
        end
      end
    end
  end

  # PATCH/PUT /order_lines/1
  # PATCH/PUT /order_lines/1.json
  def update
    order = current_user.pending_order
    old_quantity = @order_line.quantity.to_i
    @order_line.quantity = params[:quantity].to_i
    respond_to do |format|
      if @order_line.save
        total_amount = order.total_amount.to_i + @order_line.ticket.price * (params[:quantity].to_i - old_quantity)
        order.update total_amount: total_amount
        format.html { redirect_to @order_line, notice: 'Order line was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_line }
        format.js {render "create"}
      else
        format.html { render :edit }
        format.json { render json: @order_line.errors, status: :unprocessable_entity }
        format.js do
          @errors = @order_line.errors
          render "layouts/errors"
        end
      end
    end
  end

  # DELETE /order_lines/1
  # DELETE /order_lines/1.json
  def destroy
    @order_line.destroy
    respond_to do |format|
      format.html { redirect_to order_lines_url, notice: 'Order line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_line
      @order_line = OrderLine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_line_params
      params.fetch(:order_line, {})
    end
end

app/helpers/order_lines_helper.rb
module OrderLinesHelper
end

app/views/order_lines/_form.html.slim
= form_for @order_line do |f|
  - if @order_line.errors.any?
    #error_explanation
      h2 = "#{pluralize(@order_line.errors.count, "error")} prohibited this order_line from being saved:"
      ul
        - @order_line.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/order_lines/create.js.slim
|

  var text = "カート(#{current_user.pending_order.order_lines.sum(:quantity)})"
  $("#cart").children("a").text(text)
  if ($("#total_amount").length > 0) {
    $("#total_amount").text(#{current_user.pending_order.total_amount})
    $("#total_price_#{@order_line.id}").text("#{@order_line.quantity * @order_line.ticket.price}円")
  }

app/views/order_lines/edit.html.slim
h1 Editing order_line

== render 'form'

=> link_to 'Show', @order_line
'|
=< link_to 'Back', order_lines_path

app/views/order_lines/index.html.slim
h1 カート

- total_amount = 0
- @order_lines.each do |order_line|
  - total_amount += order_line.quantity * order_line.ticket.price
  .col-md-6
    = order_line.ticket.place.name
  .col-md-3
    = order_line.ticket.name
  .col-md-1
    = form_for order_line, remote: true, authenticity_token: true do |f|
      = number_field_tag :quantity, order_line.quantity, {:onchange=>'$(this.form).submit();'}
      = hidden_field_tag :type, "change"
  .col-md-2.text-right id="total_price_#{order_line.id}"
    = "#{order_line.quantity * order_line.ticket.price}円"
.col-md-12
  hr
.col-md-12.text-right
  h4#total_amount = "#{total_amount}円"
.col-md-12
  = form_for @order, remote: true do |f|
    .field
      = f.label :receiver_name
      = f.text_field :receiver_name, class: "form-control"
    .field
      = f.label :receiver_address
      = f.text_field :receiver_address, class: "form-control"
    .field
      = f.hidden_field :status, value: "bought"
    .actions 
      = f.submit "購入する", class: "btn btn-primary", type: "submit"

app/views/order_lines/new.html.slim
h1 New order_line

== render 'form'

= link_to 'Back', order_lines_path

app/views/order_lines/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_order_line_path(@order_line)
'|
=< link_to 'Back', order_lines_path