config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :order_lines
  resources :places do
    resources :tickets
  end
  root 'dashboard#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :tickets, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    unless current_user && current_user.admin?
      redirect_to root_url
    end
    @places = Place.order(created_at: :desc)
  end

  # GET /places/1
  # GET /places/1.json
  def show
    unless current_user && current_user.admin?
      redirect_to root_url
    end
  end

  # GET /places/new
  def new
    @place = Place.new
    respond_to do |format|
      format.js {render "form"}
    end
  end

  # GET /places/1/edit
  def edit
    respond_to do |format|
      format.js {render "form"}
    end
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
        format.js do
          @places = Place.order(created_at: :desc)
          render "index"
        end
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
        format.js do
          @errors = @place.errors
          render "layouts/errors"
        end
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
        format.js do
          @places = Place.order(created_at: :desc)
          render "index"
        end
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
        format.js do
          @errors = @place.errors
          render "layouts/errors"
        end
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :description, :image_url1, :image_url2, :image_url3)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.slim
= form_for @place do |f|
  - if @place.errors.any?
    #error_explanation
      h2 = "#{pluralize(@place.errors.count, "error")} prohibited this place from being saved:"
      ul
        - @place.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :image_url1
    = f.text_field :image_url1
  .field
    = f.label :image_url2
    = f.text_field :image_url2
  .field
    = f.label :image_url3
    = f.text_field :image_url3
  .actions = f.submit

app/views/places/_modal_form.html.slim
- if @place.present?
  #place-modal.modal.fade tabindex="-1" role="dialog" aria-labelledby="PlaceModal" aria-hidden="true" data-link=""
    .modal-dialog
      .modal-content
        .modal-header
          button.close type="button" data-dismiss="modal"
            span aria-hidden="true" &times;
            span.sr-only Close
          h4#place-modal-label.modal-title 観光地情報
        = form_for @place, remote: true do |f|
          .modal-body
            .field
              label 観光地名
              = f.text_field :name, class: "form-control"
            .field
              label 説明文
              = f.text_area :description, class: "form-control", rows: 10
            .field
              label 画像リンク1
              = f.text_field :image_url1, class: "form-control"
            .field
              label 画像リンク2
              = f.text_field :image_url2, class: "form-control"
            .field
              label 画像リンク3
              = f.text_field :image_url3, class: "form-control"

          .modal-footer
            = f.submit "保存", class: "btn btn-primary", type: "submit"
            button.btn.btn-default type="button" data-dismiss="modal" キャンセル

app/views/places/_places_list.html.slim
- @places.each_with_index do |place, index|
  .col-md-12
    h2 = place.name
    .col-md-6
      .carousel.slide data-ride="carousel" id="carousel-place-#{index}"
        ol.carousel-indicators
          li data-target="#carousel-place-#{index}" data-slide-to="0" class="active"
          li data-target="#carousel-place-#{index}" data-slide-to="1"
          li data-target="#carousel-place-#{index}" data-slide-to="2"
        .carousel-inner
          - no_image_link = "https://blog.stylingandroid.com/wp-content/themes/lontano-pro/images/no-image-slide.png"
          .item.active
            img src=(place.image_url1.presence || no_image_link) style="width:100%; height: 300px;"
          .item
            img src=(place.image_url2.presence || no_image_link) style="width:100%; height: 300px;"
          .item
            img src=(place.image_url3.presence || no_image_link) style="width:100%; height: 300px;"
        a.left.carousel-control href="#carousel-place-#{index}" data-slide="prev"
          span.glyphicon.glyphicon-chevron-left
          span.sr-only Previous
        a.right.carousel-control href="#carousel-place-#{index}" data-slide="next"
          span.glyphicon.glyphicon-chevron-right
          span.sr-only Next
    .col-md-6
      h5 style="white-space: pre-line" = place.description
      .actions
        = link_to 'チケット管理', place_tickets_path(place), class: "btn btn-default", remote: true
        = link_to '編集', edit_place_path(place), remote: true, class: "btn btn-primary"
        = link_to '削除', place, data: { confirm: '本当に削除しますか?' }, method: :delete, class: "btn btn-danger"

app/views/places/edit.html.slim
h1 Editing place

== render 'form'

=> link_to 'Show', @place
'|
=< link_to 'Back', places_path

app/views/places/form.js.slim
|

  var modal_form = "#{j render partial: "modal_form"}"
  $("#place-edit").html(modal_form)
  $("#place-modal").modal("show")

app/views/places/index.html.slim
.col-md-12.text-right
  = link_to '新しい観光地を追加する', new_place_path, remote: true, class: "btn btn-info"
#places-list
  = render 'places_list'
#place-edit
  = render 'modal_form'
#tickets-list
  = render 'tickets/tickets_list_modal'

app/views/places/index.js.slim
|

  var places_list = "#{j render partial: "places_list"}"
  $("#places-list").html(places_list)
  $("#place-modal").modal("hide")

app/views/places/new.html.slim
h1 New place

== render 'form'

= link_to 'Back', places_path

app/views/places/show.html.slim
p#notice = notice

p
  strong Name:
  = @place.name
p
  strong Description:
  = @place.description
p
  strong Image url1:
  = @place.image_url1
p
  strong Image url2:
  = @place.image_url2
p
  strong Image url3:
  = @place.image_url3

=> link_to 'Edit', edit_place_path(@place)
'|
=< link_to 'Back', places_path